### ISSUE TITLE
Script attempts to download image that doesn't exist

### ISSUE THREAD

**Issue by duel007** [grahampugh/docker-mwa2#1]
Unable to find image 'grahamrpugh/mwa2:latest' locally
Pulling repository docker.io/grahamrpugh/mwa2
Error: image grahamrpugh/mwa2:latest not found

**Comment by grahampugh** [comment]
My error was in the naming of the docker hub repository as "grahamrpugh/docker-mwa2", rather than "grahamrpugh/mwa2". I've now deleted the former and created the latter.
